'use client';
import { useApp } from '@/components/layout/AppProvider';
import { ShieldIcon } from '@/components/ui/Icons';
import { AdminModal } from '@/components/ui/AdminModal';

export function AdminLoginModal() {
  const { lang, showAdminLogin, closeAdminLogin, loginForm, setLoginForm, submitAdminLogin, setGuestMode } = useApp();
  return <AdminModal open={showAdminLogin} title={lang === 'hu' ? 'Mock bejelentkezés' : 'Mock login'} onClose={closeAdminLogin}><div className='stack'><div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}><span className='btn btn-secondary icon-btn' aria-hidden='true'><ShieldIcon /></span><div><p style={{ margin: 0, color: 'var(--muted)', lineHeight: 1.7 }}>{lang === 'hu' ? 'Admin vagy guest mód közti gyors demó váltás egységes felugró ablakban.' : 'Quick demo switch between admin and guest mode in the shared modal style.'}</p></div></div><div className='modal-grid' style={{ marginTop: 18 }}><label><div style={{ marginBottom: 8 }}>{lang === 'hu' ? 'Felhasználónév' : 'Username'}</div><input className='input' placeholder={lang === 'hu' ? 'Felhasználónév' : 'Username'} value={loginForm.username} onChange={(e) => setLoginForm({ ...loginForm, username: e.target.value })} /></label><label><div style={{ marginBottom: 8 }}>{lang === 'hu' ? 'Jelszó' : 'Password'}</div><input className='input' type='password' placeholder={lang === 'hu' ? 'Jelszó' : 'Password'} value={loginForm.password} onChange={(e) => setLoginForm({ ...loginForm, password: e.target.value })} /></label></div><div className='news-form-actions'><button className='btn btn-secondary' type='button' onClick={setGuestMode}>{lang === 'hu' ? 'Guest mód' : 'Guest mode'}</button><button className='btn btn-primary' type='button' onClick={submitAdminLogin}>{lang === 'hu' ? 'Admin belépés' : 'Admin login'}</button></div></div></AdminModal>;
}
